version: '3'
services:
  bot:
    build: .
    pull_policy: build
    restart: unless-stopped
    container_name: mapache-bot
    volumes:
      - .:/usr/src/app
    environment:
      - TELEGRAM_BOT_API_KEY
      - DB_PATH
