version: '3'
services:
  bot:
    pull_policy: build
    restart: unless-stopped
    container_name: inmobiliarias-scrapper
    volumes:
      - .:/usr/src/app
    environment:
      - TELEGRAM_BOT_API_KEY
