from enum import Enum


class ProcessStep(Enum):
    INITIAL = 0
    SOLOTODO_ADD_WAITING_URL = 1101
    SOLOTODO_ADD_WAITING_NAME = 1102
    SOLOTODO_EDIT_WAITING_ID = 1201
    SOLOTODO_EDIT_WAITING_ATTRIBUTE = 1202
    SOLOTODO_DELETE_WAITING_ID = 1301